### ISSUE TITLE
Incompatibility errors found when running setup script

### ISSUE THREAD

**Issue by gcpLearner0224** [google/oculi#2] opened 2019-11-05 17:13 UTC
When I ran the setup_environment.sh script most of it ran fine, but I did see a handful of errors:

ERROR: google-cloud-spanner 1.12.0 has requirement grpc-google-iam-v1<0.13dev,>=0.12.3, but you'll have grpc-google-iam-v1 0.11.4 which is incompatible.
ERROR: google-cloud-language 1.3.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.14.0, but you'll have google-api-core 1.11.1 which is incompatible.
ERROR: google-cloud-translate 2.0.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.14.0, but you'll have google-api-core 1.11.1 which is incompatible.
ERROR: google-cloud-translate 2.0.0 has requirement google-cloud-core<2.0dev,>=1.0.3, but you'll have google-cloud-core 1.0.1 which is incompatible.
ERROR: google-cloud-bigquery 1.6.2 has requirement google-cloud-core<0.30dev,>=0.28.0, but you'll have google-cloud-core 1.0.1 which is incompatible.
ERROR: tensorboard 2.0.1 has requirement grpcio>=1.24.3, but you'll have grpcio 1.21.1 which is incompatible.
ERROR: mssql-cli 0.17.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.18 which is incompatible.
ERROR: mssql-cli 0.17.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.18 which is incompatible.
ERROR: google-cloud-datastore 1.10.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.14.0, but you'll have google-api-core 1.11.1 which is incompatible.
ERROR: google-cloud-datastore 1.10.0 has requirement google-cloud-core<2.0dev,>=1.0.3, but you'll have google-cloud-core 1.0.1 which is incompatible.
ERROR: google-cloud-logging 1.14.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.14.0, but you'll have google-api-core 1.11.1 which is incompatible.
ERROR: google-cloud-logging 1.14.0 has requirement google-cloud-core<2.0dev,>=1.0.3, but you'll have google-cloud-core 1.0.1 which is incompatible.
ERROR: google-cloud-bigtable 0.31.1 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 1.0.1 which is incompatible.

Some installs were done successfully and then one final error:

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pbr-5.4.3.dist-info'
Consider using the `--user` option or check the permissions.

I do have a couple of new directories (jobs and pipeline), but I'm not sure whether these errors are showstoppers or just inconvenient. Also if there's any guidance on how to modify code or config docs to point to the correct libs, that would also be great.

**Comment by xerebus** [comment] 2019-11-07 23:43
Hi - thanks for reporting this! Are you using a virtual environment? If not, we highly recommend it - it will prevent any mismatch between already-installed versions of libraries on your machine vs. the versions that Oculi needs.

**Comment by gcpLearner0224** [comment] 2019-11-08 00:13
Hi,

I did not. I actually tried the set up script within the CLI. I will try running the virtual environment script first and then the setup script to see if there is a difference ion performance.

Thanks,

[/Users/kerry.sullivan/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1078473883]
James E. White  |  Digital Marketing Manager  |  O: +1.312.693.5211  |  M: +1.312.493.6537

**Comment by gcpLearner0224** [comment] 2019-11-08 02:19
I created the virtual environment and then ran the set up script script. I got the same errors this time as well. Do you think this will be a problem or can I move forward with the rest of the set up?

**Comment by xerebus** [comment] 2019-11-11 23:38
Hello - Unfortunately, we have been unable to reproduce this error across multiple environments. You should certainly continue and see if you get further failures, but the errors provided (especially the EnvironmentError) are specific to your local environment. Please ensure the virtual environment was set up successfully to fully isolate your current system from the runtime environment.

Closing - can't reproduce

**Closed as completed by xerebus** 2019-11-11 23:38 UTC
